/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MDataByFix.java
 *
 * Created on 2011-8-8, 11:18:23
 */
package main;


import MyQuickfix.GetTradeData;

import java.util.logging.Level;
import java.util.logging.Logger;

import util.configClass;
/**
 *
 * @author Administrator
 */
public class TradeDataByFix extends javax.swing.JFrame {

    /** Creates new form MDataByFix */
    public TradeDataByFix() {
        initComponents(); 
    }
    public static String fixIP;
    public static String fixPort;
    GetTradeData gm;
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle(configClass.getTitle());

        jButton1.setText("Start!");
        jButton1.setName("jButton1"); // NOI18N
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        jLabel1.setText("not logon");
        jLabel1.setName("jLabel1"); // NOI18N

        jLabel2.setText("FixServerIP");
        jLabel2.setName("jLabel2"); // NOI18N

        jLabel3.setText("FixServerPort");
        jLabel3.setName("jLabel3"); // NOI18N

        jTextField1.setText(configClass.getserverIP());// for real 
       //jTextField1.setText("210.13.87.3");// for demo
       //jTextField1.setText("211.144.195.153");// for real 
        jTextField1.setName("jTextField1"); // NOI18N

        jTextField2.setText(configClass.getserverPort());
        jTextField2.setName("jTextField2"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField2)
                            .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE)
                            .addComponent(jButton1))))
                .addContainerGap(148, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 77, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(72, 72, 72)
                .addComponent(jLabel1)
                .addGap(26, 26, 26))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void  updateIsService(boolean bb){
        if(bb){
            this.jLabel1.setText("Service");
            this.jButton1.setEnabled(false);
        }
        else{
            this.jLabel1.setText("UnService");
            this.jButton1.setEnabled(false);
        }
    }
/**
 * 
 *  Function: to start the program
 *
 *   JohnnyLiu  DateTime 2012-6-13 1:59:31
 *  
 */
    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        fixIP = this.jTextField1.getText();
        fixPort = this.jTextField2.getText();
        gm = new GetTradeData(this);
        //gm.login("ESolution1");
        gm.login();
        
    }//GEN-LAST:event_jButton1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new TradeDataByFix().setVisible(true);
            }
        });
    }
    public void Reconnect()
    {
    	gm.logout();
    	//gm.login("DRW");
    	gm.login();
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
